name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        env:
          PIP_NO_CACHE_DIR: 1
          BUILDOZER_WARN_ON_ROOT: 0
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: package
          path: bin/*.apk
