name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Fix ownership
        run: |
          chown -R root:root .

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: package
          path: bin/*.apk
